---

- name: Include vars file if provided
  when: freeipa_config_vars_file | length > 0
  ansible.builtin.include_vars:
    file: "{{ freeipa_config_vars_file }}"

- name: Verify FreeIPA authentication
  freeipa.ansible_freeipa.ipaconfig:
    ipaadmin_principal: "{{ freeipa_config_admin_principal }}"
    ipaadmin_password: "{{ freeipa_config_password }}"
  register: ipa_test
  changed_when: false
  no_log: true

- name: Verify version output
  ansible.builtin.assert:
    that:
      - not ipa_test.failed
      - ipa_test.config.ca_renewal_master_server == inventory_hostname

- name: Set initial global defaults
  freeipa.ansible_freeipa.ipaconfig:
    ipaadmin_password: "{{ freeipa_config_password }}"
    defaultshell: "{{ freeipa_config_defaults.defaultshell }}"
    homedirectory: "{{ freeipa_config_defaults.homedirectory }}"
    ipaapi_context: server

- name: Create users
  freeipa.ansible_freeipa.ipauser:
    ipaadmin_password: "{{ freeipa_config_password }}"
    users: "{{ freeipa_config_users }}"
    update_password: on_create
    ipaapi_context: server

- name: Create user groups
  freeipa.ansible_freeipa.ipagroup:
    ipaadmin_password: "{{ freeipa_config_password }}"
    groups: "{{ freeipa_config_user_groups }}"
    ipaapi_context: server

- name: Configure sudo rules
  freeipa.ansible_freeipa.ipasudorule:
    ipaadmin_password: "{{ freeipa_config_password }}"
    sudorules: "{{ freeipa_config_sudo_rules }}"
    ipaapi_context: server

- name: Set global defaults after config
  freeipa.ansible_freeipa.ipaconfig:
    defaultgroup: "{{ freeipa_config_defaults.defaultgroup }}"
    ipaadmin_password: "{{ freeipa_config_password }}"

- name: Set global password policy
  freeipa.ansible_freeipa.ipapwpolicy:
    name: global_policy
    ipaadmin_password: "{{ freeipa_config_password }}"
    maxlife: 180
    ipaapi_context: server

...
